settings:
  num_clients: 2
  num_replicas: 3
  log_level: DEBUG
  consistency_schemes: [sequential, eventual, linear, casual]
  main:
    ip: localhost
    port: 9000
  client:
    ip: localhost
    port: 9200
    command_file: commands/client-commands.txt
  replica:
    ip: localhost
    port: 9400
    # output_file: result.txt
    